---
- name: Head node configuration
  become: yes
  hosts: head
  tasks:
    
  - name: Step 1 Configure EPEL repo
    include_tasks: tasks/epel.yml

  - name: Step 1 Install head node packages & enable powertools repo
    include_tasks: tasks/head-node-pkgs.yml

  - name: Step 2 Setup slurm user & groups on head node
    include_tasks: tasks/slurm-user.yml
  
  - name: Step 3 Setup slurm log file & ownership on headnode
    include_tasks: tasks/slurm-logs.yml

  - name: Step 4 Setup munge
    include_tasks: tasks/munge.yml

  - name: Step 5 Build slurm rpms and install on headnode
    include_tasks: tasks/slurm-rpm-build.yml

- name: Compute node configuration
  become: yes
  hosts: all_nodes
  tasks:

  - name: Step 1 Configure EPEL repo
    include_tasks: tasks/epel.yml

  - name: Step 2 Install compute node packages & enable powertools repo
    include_tasks: tasks/compute-node-pkgs.yml

  - name: Step 3 Install munge, sync key, and restart services
    include_tasks: tasks/mungekey.yml

  - name: Step 4 Setup slurm user & group
    include_tasks: tasks/slurm-user.yml

  - name: Step 5 Deploy & configure slurmd
    include_tasks: tasks/slurmd-computenode.yml
