  - name: Enable the EPEL repo
    ansible.builtin.dnf:
      name: epel-release
      state: latest

  - name: Ensure time zones are in sync
    ansible.builtin.command:
      cmd: timedatectl set-timezone EST
