  - name: Install Munge (needed for authentication)
    ansible.builtin.dnf:
      name: munge,munge-libs,munge-devel
      state: latest

  - name: Check that the somefile.conf exists
    stat:
      path: /etc/munge/munge.key
    register: stat_result

  - name: Create the file, if it doesnt exist already
    ansible.builtin.command:
     cmd: /usr/sbin/create-munge-key -r
    when: not stat_result.stat.exists
