  - name: Install Munge through DNF
    ansible.builtin.dnf:
      name: munge,munge-libs,munge-devel
      state: latest

  - name: Check if the munge.key exists
    stat:
      path: /etc/munge/munge.key
    register: stat_result

  - name: Create munge.key
    ansible.builtin.command:
     cmd: /usr/sbin/create-munge-key -r
    when: not stat_result.stat.exists
