  - name: Install Munge needed for authentication
    ansible.builtin.dnf:
      name: munge,munge-libs,munge-devel
      state: latest

  - name: Check if the munge.key exists
    stat:
      path: /etc/munge/munge.key
    register: stat_result

  - name: Create the munge.key file, if it doesnt exists
    ansible.builtin.command:
     cmd: /usr/sbin/create-munge-key -r
    when: not stat_result.stat.exists

  - name: Restart munge service after munge.key has been created
    ansible.builtin.service:
     name: munge
     state: restarted
