  - name: Copy mungekey with owner and permissions to the compute nodes
    ansible.builtin.copy:
     src: /etc/munge/munge.key
     dest: /etc/munge/
     owner: munge
     group: munge
     mode: '0600'

  - name: Restart munge service after munge.key has been copied
    ansible.builtin.service:
     name: munge
     state: restarted
