---

- hosts: head

  - name: Give insecure permissions to /etc/munge
    ansible.builtin.file:
      path: /etc/munge
      owner: munge
      group: munge
      mode: '0455'

  - name: Give insecure permissions to /etc/munge/munge.key
    ansible.builtin.file:
      path: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: '0455'

- hosts: all_nodes

  tasks:
  - name: Copy mungekey with owner and permissions to the compute nodes
    ansible.builtin.copy:
     src: /etc/munge/munge.key
     dest: /etc/munge/
     owner: munge
     group: munge
     mode: '0600'

  - name: Restart munge service after munge.key has been copied
    ansible.builtin.service:
     name: munge
     state: restarted

- hosts: head
  tasks:
  - name: Give secure permissions back to /etc/munge/munge.key
    ansible.builtin.file:
      path: /etc/munge/munge.key
      owner: munge
      group: munge
      mode: '0400'

  - name: Give secure permissions back to /etc/munge
    ansible.builtin.file:
      path: /etc/munge
      owner: munge
      group: munge
      mode: '0700'
