---
- hosts: head

  tasks:

  - name: Copy mariadb-server.cnf into place
    ansible.builtin.copy:
     src: /home/instructor/lci-labs/files/mariadb-server.cnf
     dest: /etc/my.cnf.d/

  - name: delete anonymous MySQL server user for {{ ansible_hostname }}
    community.mysql.mysql_user:
      name: ''
      host: localhost
      state: absent

  - name: remove the MySQL test database
    community.mysql.mysql_db:
      name: test
      state: absent

  - name: Change root user password on first run
    community.mysql.mysql_user: login_user=root
     login_password=''
     name=root
     password=lcilab2022
     priv=*.*:ALL,GRANT
     host={{ item }}
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: Restart mariadb service
    ansible.builtin.service:
     name: mariadb
