---
- hosts: all_nodes

  tasks:

  - name: Copy compute node RPMs
    ansible.builtin.copy: src={{ item.src }} dest={{ item.dest}}
    become: yes
    become_user: root
    with_items:
    - { src: '/etc/slurm/slurm.conf', dest: '/etc/slurm/' }
    - { src: '/home/instructor/lci-labs/packages/compute/slurm-22.05.2-1.el8.x86_64.rpm', dest: '/tmp' }
    - { src: '/home/instructor/lci-labs/packages/compute/slurm-perlapi-22.05.2-1.el8.x86_64.rpm', dest: '/tmp' }
    - { src: '/home/instructor/lci-labs/packages/compute/slurm-slurmd-22.05.2-1.el8.x86_64.rpm', dest: '/tmp' }
    - { src: '/home/instructor/lci-labs/packages/compute/slurm-libpmi-22.05.2-1.el8.x86_64.rpm', dest: '/tmp' }

  - name: Install compute node RPMs
    ansible.builtin.dnf:
      name: /tmp/slurm-22.05.2-1.el8.x86_64.rpm,/tmp/slurm-perlapi-22.05.2-1.el8.x86_64.rpm,/tmp/slurm-slurmd-22.05.2-1.el8.x86_64.rpm,/tmp/slurm-libpmi-22.05.2-1.el8.x86_64.rpm
      disable_gpg_check: yes
      state: present

  - name: Create & change ownership of /etc/slurm/
    file:
      path: /etc/slurm
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy slurm.conf into place with correct permissions
    ansible.builtin.copy:
     src: /home/instructor/lci-labs/files/slurm.conf
     dest: /etc/slurm/
     owner: slurm
     group: slurm
     mode: '0755'

  - name: Copy cgroup.conf into place with correct permissions
    ansible.builtin.copy:
     src: /home/instructor/lci-labs/files/cgroup.conf
     dest: /etc/slurm/

  - name: Restart slurmd service
    ansible.builtin.service:
     name: slurmd
     enabled: yes
     state: restarted
