---
- hosts: head
  tasks:
  - name: Create a new database named slurm_acct_db
    community.mysql.mysql_db:
      name: slurm_acct_db
      state: present

  - name: Create database user slurm with slurm_acct_db privileges
    community.mysql.mysql_user:
      name: slurm
      password: "lcilab2022"
      priv: 'slurm_acct_db.*:all,GRANT'
      state: present

