---
- hosts: localhost

  tasks:
  - name: Create & change ownership of /var/spool/slurm directory
    file:
      path: /var/spool/slurm
      state: directory
      owner: slurm
      group: slurm
      mode: 0755

  - name: Create & change ownership of /var/spool/slurmctld directory
    file:
      path: /var/spool/slurmctld
      state: directory
      owner: slurm
      group: slurm
      mode: 0755

  - name: Creating the slurmctld log file
    ansible.builtin.file:
      path: /var/log/slurmctld
      state: touch
      owner: slurm
      group: slurm 

  - name: Creating the slurm job_acct log file
    ansible.builtin.file:
      path: /var/log/slurm_jobacct.log
      state: touch
      owner: slurm
      group: slurm

  - name: Creating the slurm jobcomp log file
    ansible.builtin.file:
      path: /var/log/slurm_jobcomp.log
      state: touch
      owner: slurm
      group: slurm

  - name: ensure file exists
    copy:
      content: ""
      dest: /etc/nologin
      force: no
      group: slurm
      owner: slurm
      mode: 0555
